# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'DevOCFramwork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DevOCFramwork
pod “AFNetworking”
pod “SDWebImage”
pod “YYModel”
pod “FMDB”
pod “SVProgressHUD”
pod “pop”

  target 'DevOCFramworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DevOCFramworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
